#!/usr/bin/env bash
""":"
exec "$(dirname "$0")/Chaturdown_Venv/bin/python3" "$0" "$@"
":"""

"""
Chaturdown — Chaturbate Multi-User Watcher & Downloader (TUI Edition)
-------------------------------------------------------------------------
Polls multiple Chaturbate usernames via the public API.
Features a clean, interactive Terminal User Interface (TUI) to monitor
downloads in real-time without scrolling logs.

Errors and crashes surface in your normal terminal (with tracebacks).
A catalog of common failure cases + fixes lives in the development plan.
"""

import curses
import datetime
import random
import re
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path

_STOP = threading.Event()  # set to stop all threads cleanly

try:
    import requests
except ImportError:
    print("❌ Missing dependency: 'requests' not found.")
    print("👉 Did you forget to run the ./setup.sh file first?")
    sys.exit(1)


# ============================================================
# USER CONFIGURATION (Edit these values before running)
# ============================================================

CB_USERNAMES = [
    "model1",
    "model2",
    "lucindascercy",
]

# Paths (Downloads will go directly to VIDEOS_DIR / username)
# The download history log now lives directly next to this script (no separate Logs/ folder needed).
VIDEOS_DIR_STR   = "./Videos"
DOWNLOAD_LOG_STR = "./Chatur_download_logs.txt"

# If yt-dlp is installed globally, leave as "yt-dlp". 
YTDLP_EXE_STR    = "yt-dlp"

# yt-dlp self-update interval (seconds). 0 = disabled. Default: once per day.
YTDLP_UPDATE_INTERVAL = 86400

# Polling and Timeout Settings (in seconds)
POLL_MIN      = 60     
POLL_MAX      = 120    
STALL_TIMEOUT = 60     # seconds of stdout silence before declaring a stall
# MUX_TIMEOUT removed — downloads write directly to final file; no separate mux phase to wait for.

# ============================================================
# END OF USER CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

def resolve_path(p_str: str) -> Path:
    p = Path(p_str).expanduser()
    return p if p.is_absolute() else (BASE_DIR / p).resolve()

VIDEOS_DIR   = resolve_path(VIDEOS_DIR_STR)
DOWNLOAD_LOG = resolve_path(DOWNLOAD_LOG_STR)
YTDLP_EXE    = resolve_path(YTDLP_EXE_STR) if ("/" in YTDLP_EXE_STR or "\\" in YTDLP_EXE_STR) else YTDLP_EXE_STR

COOKIES_FILE = BASE_DIR / "Chaturdown_Cookies.txt"
UA_TXT       = BASE_DIR / "user_agent.txt"

# Read dynamic user-agent generated by ./ChaturLogin.py
if UA_TXT.exists():
    USER_AGENT = UA_TXT.read_text().strip()
else:
    print("❌ FATAL: user_agent.txt is missing.")
    print("   This file is created by running ./ChaturLogin.py")
    print("   Fix:")
    print("      1. Run ./ChaturLogin.py to generate fresh cookies and user_agent.txt")
    print("      2. Re-run Chaturdown.py")
    sys.exit(1)

# Create base folders
VIDEOS_DIR.mkdir(parents=True, exist_ok=True)
# Ensure the folder for the download history log exists (the log itself now lives directly in BASE_DIR)
DOWNLOAD_LOG.parent.mkdir(parents=True, exist_ok=True)

# ============================================================================
# TUI SHARED STATE (The "Scoreboard")
# ============================================================================
SHARED_STATE = {}

# --- Dynamic TUI footer status (the only persistent on-screen status line) ---
API_STATUS = "Status: Connected to Chaturbate API"

def set_api_status(msg: str) -> None:
    global API_STATUS
    API_STATUS = msg

def format_time(seconds):
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def format_size(size_bytes: int) -> str:
    """Format bytes as MB or GB (matches the style from the demo tui.py)."""
    if size_bytes <= 0:
        return "0.0 MB"
    mb = size_bytes / (1024 * 1024)
    if mb >= 1024:
        return f"{mb/1024:.2f} GB"
    return f"{mb:.1f} MB"

# Remove ANSI escape codes from yt-dlp output (prevents curses rendering issues)
ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

# Note: File-based error logging has been intentionally removed.
# All errors surface in the terminal via standard Python tracebacks.

# ============================================================================
# LIVE DETECTION
# ============================================================================
def _cb_session() -> requests.Session:
    session = requests.Session()
    session.headers["User-Agent"] = USER_AGENT
    if COOKIES_FILE.exists():
        for line in COOKIES_FILE.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 7:
                domain, _, path_, _, _, name, value = parts[:7]
                session.cookies.set(name, value, domain=domain.lstrip("."), path=path_)
    return session

def check_is_live(username: str) -> bool:
    try:
        r = _cb_session().get(f"https://chaturbate.com/api/chatvideocontext/{username}/", timeout=15)
        r.raise_for_status()
        if not r.text.strip():
            set_api_status("Status: Session may need re-login (empty API response)")
            return False
        set_api_status("Status: Connected to Chaturbate API")
        return r.json().get("room_status") == "public"
    except ValueError:
        set_api_status("Status: Cloudflare blocked — run ./ChaturLogin.py to refresh cookies")
        _STOP.set()
        return False
    except Exception as e:
        set_api_status("Status: Unable to connect, check connection or try re-logging back in.")
        # Real network errors will naturally produce tracebacks when they are fatal
        return False

def check_all_users(usernames: list[str]) -> list[str]:
    live: list[str] = []
    lock = threading.Lock()

    def _check(u):
        if check_is_live(u):
            with lock:
                live.append(u)

    threads = [threading.Thread(target=_check, args=(u,)) for u in usernames if u]
    for t in threads: t.start()
    for t in threads: t.join()
    return live

# ============================================================================
# FILE SIZE HELPER
# ============================================================================
def get_download_size(target_file: Path) -> int:
    """Calculates the size of the target file using pattern matching."""
    try:
        return sum(f.stat().st_size for f in target_file.parent.glob(f"{target_file.stem}*") if f.is_file())
    except Exception:
        return 0

# ============================================================================
# STALL WATCHDOG
#
# Detects when yt-dlp stops making progress (no stdout for STALL_TIMEOUT seconds).
# On stall we attempt a graceful stop (SIGINT) so the final file is left in a
# consistent state. Because downloads write directly to the final .mkv (no
# separate fragment/mux phase), we no longer perform file-size-based mux
# monitoring after SIGINT.
# ============================================================================
class StallWatchdog:
    def __init__(self, process: subprocess.Popen, target_file: Path):
        self.process = process
        self.target_file = target_file
        self._stopped = False
        self._lock = threading.Lock()
        self.last_output_t = time.time()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        with self._lock: self._stopped = True

    def ping(self):
        with self._lock: self.last_output_t = time.time()

    def _run(self):
        while True:
            time.sleep(10)
            with self._lock:
                if self._stopped: return
                silence = time.time() - self.last_output_t
            if self.process.poll() is not None: return
            if silence > STALL_TIMEOUT:
                set_api_status("Status: Stall detected — download stopped")
                _terminate_process(self.process, "Stall detected")
                return

def _terminate_process(process: subprocess.Popen, reason: str):
    """Attempt graceful termination of yt-dlp (SIGINT), then hard kill if needed.
    Downloads write directly to the final .mkv file (no separate fragments or post-download mux phase),
    so we no longer monitor file-size growth after SIGINT.
    """
    if process.poll() is not None:
        return
    try:
        process.send_signal(signal.SIGINT)
    except Exception:
        pass

    # Wait up to 30 seconds for clean exit after SIGINT
    for _ in range(30):
        if process.poll() is not None:
            return
        time.sleep(1)

    # Still alive → hard kill
    try:
        process.kill()
    except Exception:
        pass

# ============================================================================
# DOWNLOAD ENGINE
# ============================================================================
def _next_filename(username: str) -> Path:
    out_folder = VIDEOS_DIR / username
    out_folder.mkdir(parents=True, exist_ok=True)
    
    existing = []
    for f in out_folder.glob(f"{username}_*.mkv"):
        m = re.match(rf"^{re.escape(username)}_(\d+)\.mkv$", f.name)
        if m: existing.append(int(m.group(1)))
        
    next_n = (max(existing) + 1) if existing else 1
    return out_folder / f"{username}_{next_n:03d}.mkv"

def _build_ytdlp_cmd(username: str, output_path: Path) -> list[str]:
    cmd = [
        str(YTDLP_EXE),
        f"https://chaturbate.com/{username}/",
        "--output", str(output_path),
        "--user-agent", USER_AGENT,
        "--hls-use-mpegts",
        "--merge-output-format", "mkv",
        "--fragment-retries", "5",
        "--retries", "5",
        "--no-part",
    ]
    if COOKIES_FILE.exists():
        cmd += ["--cookies", str(COOKIES_FILE)]
    return cmd

def _maybe_update_yt_dlp():
    """Check once per day and silently upgrade yt-dlp if needed.
    Failures are completely ignored — the script will just continue
    with the currently installed version. User does not need to know.
    """
    if YTDLP_UPDATE_INTERVAL <= 0:
        return
    last_file = BASE_DIR / ".last_yt_dlp_update"
    now = time.time()
    if last_file.exists():
        try:
            last = float(last_file.read_text().strip())
            if now - last < YTDLP_UPDATE_INTERVAL:
                return
        except Exception:
            pass

    try:
        # As specified by user. Using sys.executable ensures the correct
        # pip inside the Chaturdown_Venv (robust even if "pip" is not in PATH).
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--upgrade", "yt-dlp"],
            check=False, capture_output=True, text=True, timeout=180
        )
        # Alternative the user also mentioned:
        # subprocess.run([str(YTDLP_EXE), "-U"], check=False,
        #                capture_output=True, text=True, timeout=180)
        last_file.write_text(str(now))
    except Exception:
        # Say nothing on any failure.
        pass

def _log_download(filename: str) -> None:
    today = datetime.date.today()
    date_str = f"{today.day}/{today.month}/{today.year}"
    cutoff = today - datetime.timedelta(days=2)

    existing = DOWNLOAD_LOG.read_text() if DOWNLOAD_LOG.exists() else ""
    lines = existing.rstrip("\n").split("\n") if existing.strip() else []
    if lines and lines[-1] == date_str:
        lines.append(filename)
    else:
        if lines: lines.append("")
        lines.extend([date_str, filename])

    pruned: list[str] = []
    skip_block = False
    for ln in lines:
        m = re.fullmatch(r"(\d{1,2})/(\d{1,2})/(\d{4})", ln)
        if m:
            try:
                block_date = datetime.date(int(m.group(3)), int(m.group(2)), int(m.group(1)))
                skip_block = block_date < cutoff
            except ValueError:
                skip_block = False
        if not skip_block:
            pruned.append(ln)

    while pruned and pruned[0] == "": pruned.pop(0)
    DOWNLOAD_LOG.write_text("\n".join(pruned) + "\n")


def download_stream(username: str) -> None:
    output_path = _next_filename(username)
    SHARED_STATE[username]["target"] = output_path  # for TUI file-size display (replaces broken prog)

    # Startup messages are intentionally minimal to keep the TUI clean.
    
    process = subprocess.Popen(
        _build_ytdlp_cmd(username, output_path),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    watchdog = StallWatchdog(process, output_path)

    try:
        for line in process.stdout:
            clean_line = ansi_escape.sub('', line.strip()) # Strip ANSI colors
            if not clean_line: continue
            watchdog.ping()

            # Live file size for the TUI is tracked by polling the output file (see get_download_size).
            if "giving up after" in clean_line.lower() or "unable to download" in clean_line.lower():
                set_api_status(f"Status: Stream error for {username}")
                watchdog.stop()
                _terminate_process(process, "Stream ended")
                break

    except KeyboardInterrupt:
        set_api_status(f"Status: Interrupted while downloading {username}")
        _terminate_process(process, "User interrupt")
        watchdog.stop()
        SHARED_STATE[username]["target"] = None
        _log_download(output_path.name)
        raise

    watchdog.stop()
    process.wait()

    if process.returncode != 0:
        set_api_status(f"Status: yt-dlp failed for {username} (code {process.returncode})")

    _log_download(output_path.name)
    SHARED_STATE[username]["target"] = None

# ============================================================================
# WATCHER LOOP
# ============================================================================
_active: dict[str, threading.Thread] = {}
_active_lock = threading.Lock()

def _is_active(username: str) -> bool:
    with _active_lock:
        t = _active.get(username)
        if t is None: return False
        if not t.is_alive():
            del _active[username]
            return False
        return True

def _launch(username: str):
    SHARED_STATE[username]["start_t"] = time.time()  # Start the timer instantly
    
    def _run():
        try:
            download_stream(username)
        except Exception:
            import traceback
            traceback.print_exc()  # Makes the crash visible in the user's terminal
            set_api_status(f"Status: Crash in download thread for {username} (see terminal)")
            _STOP.set()
        finally:
            with _active_lock: _active.pop(username, None)
            SHARED_STATE[username]["status"] = "Offline"
            SHARED_STATE[username]["progress"] = ""
            SHARED_STATE[username]["target"] = None
        
    t = threading.Thread(target=_run, daemon=True)
    with _active_lock: _active[username] = t
    t.start()

def watch_loop(usernames: list[str]):
    # "TUI Watcher Initializing..." intentionally removed (user requested quiet TUI — no more startup spam)

    # Note: The missing cookies check now happens early in main() with a terminal-only error.
    # so we no longer need the late check here.

    attempt = 0
    try:
        while not _STOP.is_set():
            attempt += 1
            _maybe_update_yt_dlp()
            live_users = check_all_users(usernames)

            for u in usernames:
                is_live = u in live_users
                is_dl = _is_active(u)

                # Unified Status Logic: If they are live or downloading, they are "Online"
                if is_live or is_dl:
                    SHARED_STATE[u]["status"] = "Online"
                    if is_live and not is_dl:
                        _launch(u)
                else:
                    SHARED_STATE[u]["status"] = "Offline"
                    SHARED_STATE[u]["progress"] = ""
                    SHARED_STATE[u]["target"] = None

            snooze = random.randint(POLL_MIN, POLL_MAX)
            for _ in range(snooze): # Breakable sleep
                if _STOP.is_set(): break
                time.sleep(1)
    except Exception:
        import traceback
        traceback.print_exc()
        set_api_status("Status: Fatal error in watcher thread (see terminal for details)")
        _STOP.set()

# ============================================================================
# TUI DISPLAY LOGIC
# ============================================================================
def draw_dashboard(stdscr):
    curses.curs_set(0)
    stdscr.timeout(500)

    # Initialize shared state dictionary
    for u in CB_USERNAMES:
        if u not in SHARED_STATE:
            SHARED_STATE[u] = {"status": "Offline", "progress": "", "start_t": time.time(), "target": None}

    while not _STOP.is_set():
        max_y, max_x = stdscr.getmaxyx()
        stdscr.clear()

        try:
            stdscr.box()
            stdscr.addstr(2, 4, "📡 CHATURBATE MULTI-DOWNLOADER TUI", curses.A_BOLD)
            stdscr.addstr(3, 4, "─" * (max_x - 8))

            row = 5
            # More models can now be shown — the old System Log window is gone.
            for u in CB_USERNAMES:
                if row >= max_y - 4: break

                s = SHARED_STATE.get(u, {})
                status = s.get("status", "Offline")
                name_pad = u.ljust(16)

                if status == "Online":
                    elapsed = time.time() - s.get("start_t", time.time())
                    t_str = format_time(elapsed)

                    # Live file size (replaces the broken/unreliable {prog} yt-dlp parsing)
                    target = s.get("target")
                    size_b = get_download_size(Path(target)) if target else 0
                    size_str = format_size(size_b).rjust(8)
                    line = f"🟢 {name_pad} | Online  | ⏱️ {t_str} | 💾 {size_str}"
                else:
                    line = f"🔴 {name_pad} | Offline"

                stdscr.addstr(row, 4, line[:max_x-6])
                row += 1

            stdscr.addstr(row + 1, 4, "─" * (max_x - 8))

            # The only two persistent status lines (user request).
            # Status (connection or last error) at max_y-2, quit hint directly under it.
            stdscr.addstr(max_y - 2, 4, API_STATUS[:max_x-6], curses.A_BOLD)
            stdscr.addstr(max_y - 1, 4, "Press 'q' to stop the script.", curses.A_DIM)

        except curses.error:
            pass # Ignore render errors caused by dragging/resizing terminal window

        key = stdscr.getch()
        if key == ord('q') or key == ord('Q'):
            _STOP.set()
            break

# ============================================================================
# EXECUTION
# ============================================================================
def main():
    usernames = [u.strip() for u in CB_USERNAMES if u.strip()]
    if not usernames:
        print("❌ Error: No usernames found in the CB_USERNAMES list.")
        sys.exit(1)

    # Hard requirement: cookies must exist before we even start the TUI.
    # This must be a terminal-only error (no TUI flashing).
    if not COOKIES_FILE.exists() or COOKIES_FILE.stat().st_size < 100:
        print("❌ FATAL: Chaturdown_Cookies.txt is missing or empty.")
        print()
        print("   This script cannot run without valid login cookies.")
        print(f"   Expected location: {COOKIES_FILE}")
        print()
        print("Fix:")
        print("   1. Run ./ChaturLogin.py to generate fresh cookies.")
        print("   2. Make sure the file is saved as 'Chaturdown_Cookies.txt' in this same folder.")
        print("   3. Re-run Chaturdown")
        sys.exit(1)

    # 1. Start the API watcher and Downloader in the background
    watcher_thread = threading.Thread(target=watch_loop, args=(usernames,), daemon=True)
    watcher_thread.start()

    # 2. Give the main screen over to the Curses TUI
    curses.wrapper(draw_dashboard)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        _STOP.set()
    except Exception:
        # Make sure the terminal is usable even if curses is in a bad state
        try:
            curses.endwin()
        except Exception:
            pass
        print("\n💥 The script encountered an unexpected error.")
        print("   A full traceback should appear above (or in your terminal scrollback).")
        print("   Common causes and fixes are documented in the script header and the plan.")
        raise  # Re-raise so the real traceback is still visible
    finally:
        print("\n👋 TUI Closed. Terminal restored cleanly!")
